In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset=dataset.astype(int)

In [6]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [7]:
dataset=dataset.drop("User ID",axis=1)

In [8]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [9]:
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
dep=dataset["Purchased"]

In [10]:
indep.shape

(400, 3)

In [11]:
dep

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int32

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [16]:
from sklearn.model_selection import GridSearchCV

param_grid={'n_neighbors':[3,5,7,9],
            'weights':['uniform','distance'],
            'algorithm':['auto','ball_tree','kd_tree','brute'],
            'metric':['minkowski','euclidean','manhattan',]}

grid=GridSearchCV(KNeighborsClassifier(),  param_grid, refit=True, verbose=3, n_jobs=-1,scoring='f1')

grid.fit(x_train,y_train)

Fitting 5 folds for each of 96 candidates, totalling 480 fits

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'metric': ['minkowski', 'euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9],
                         'weights': ['uniform', 'distance']},
             scoring='f1', verbose=3)

In [17]:
re=grid.cv_results_
grid_predictions=grid.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)

from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)

In [18]:
table=pd.DataFrame.from_dict(re)

In [19]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006248,0.007652,0.024992,0.007653,auto,minkowski,3,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.756757,0.727273,0.628571,0.717949,0.648649,0.695840,0.048867,1
1,0.003124,0.006248,0.012498,0.006249,auto,minkowski,3,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.777778,0.645161,0.611111,0.685714,0.650000,0.673953,0.057043,29
2,0.003124,0.006248,0.018746,0.006247,auto,minkowski,5,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.648649,0.628571,0.545455,0.800000,0.717949,0.668125,0.085866,37
3,0.003124,0.006248,0.009373,0.007653,auto,minkowski,5,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.756757,0.625000,0.571429,0.722222,0.631579,0.661397,0.067973,73
4,0.012497,0.006248,0.020348,0.006593,auto,minkowski,7,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.628571,0.736842,0.606061,0.750000,0.611111,0.666517,0.063371,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,0.004928,0.007612,0.011418,0.005511,brute,manhattan,5,distance,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.756757,0.625000,0.571429,0.722222,0.631579,0.661397,0.067973,73
92,0.003125,0.006249,0.018745,0.006247,brute,manhattan,7,uniform,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.628571,0.736842,0.606061,0.750000,0.611111,0.666517,0.063371,49
93,0.009372,0.007652,0.006249,0.007653,brute,manhattan,7,distance,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.742857,0.645161,0.571429,0.722222,0.615385,0.659411,0.064484,85
94,0.009373,0.007653,0.018746,0.006248,brute,manhattan,9,uniform,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.666667,0.702703,0.685714,0.780488,0.611111,0.689337,0.055015,22
95,0.009372,0.007653,0.009373,0.007653,brute,manhattan,9,distance,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.722222,0.687500,0.571429,0.722222,0.615385,0.663752,0.060439,61

In [20]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter{}".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter{'algorithm': 'auto', 'metric': 'minkowski', 'n_neighbors': 3, 'weights': 'uniform'} 0.7681406676150806

In [21]:
print(cm)

[[70 15]
 [16 33]]

In [22]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.81      0.82      0.82        85
           1       0.69      0.67      0.68        49

    accuracy                           0.77       134
   macro avg       0.75      0.75      0.75       134
weighted avg       0.77      0.77      0.77       134